config/routes.rb
Journalv2::Application.routes.draw do

  resources :users do 
    resources :journals do
      resources :entries
    end
  end

   root :to => 'entries#index'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :body, :title, :journal_id

  belongs_to :journal
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  attr_accessible :description, :name, :private, :user_id

  belongs_to :user
  has_many :entries
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :active, :first_name, :last_name, :password, :password_confirmation, :username

  has_many :journals

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.json
  #
  #
  before_filter :get_user_and_journal_and_entries

  def get_user_and_journal_and_entries
    @user = User.find(params[:user_id])
    @journal = @user.journals.find(params[:journal_id])
    @entries = @journal.entries
  end

  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = @entries.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new

   # @user = User.find_by_id(params[:user_id])i
   # @journal = @user.journals.find(params[:journal_id])


    @entry = @entries.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = @entries.find(params[:id])
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = @entries.new(params[:entry])

    respond_to do |format|
      if @entry.save
        format.html { redirect_to user_journal_entries_path, notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = @entries.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to user_journal_entries_path(@user, @journal), notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = @entries.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to user_journal_entries_url(@user, @journal) }
      format.json { head :no_content }
    end
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  # GET /journals
  # GET /journals.json
  before_filter :get_user_and_journals

  def get_user_and_journals
    @user = User.find(params[:user_id])
    @journals = @user.journals
  end

  def index

    @journals = @journals.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @journals }
    end
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
    
    @journal = @journals.find(params[:id])

    @entries = @journal.entries.all

    redirect_to user_journal_entries_path(@user, @journal)

  end

  # GET /journals/new
  # GET /journals/new.json
  def new
    @journal = @journals.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @journal }
    end
  end

  # GET /journals/1/edit
  def edit
    @journal = Journal.find(params[:id])
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = @journals.new(params[:journal])

    respond_to do |format|
      if @journal.save
        format.html { redirect_to [@user, @journal], notice: 'Journal was successfully created.' }
        format.json { render json: @journal, status: :created, location: @journal }
      else
        format.html { render action: "new" }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /journals/1
  # PUT /journals/1.json
  def update
    @journal = @journals.find(params[:id])

    respond_to do |format|
      if @journal.update_attributes(params[:journal])
        format.html { redirect_to @journal, notice: 'Journal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal = @journals.find(params[:id])
    @journal.destroy

    respond_to do |format|
      format.html { redirect_to journals_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

def index
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    redirect_to user_journals_path(@user)
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/_form.html.erb
<%= form_for([@user, @journal, @entry]) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <section id="form">
  <div class="field">
    <%= f.label :title %> <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %> <%= f.text_area :body, style: "width: 500px; height: 200px;" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </section>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
          <!-- This code is taken from http://twitter.github.com/bootstrap/examples/hero.html -->

          <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
              <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </a>
                <a class="brand" href="#">LiveJournal 2.0</a>
                <div class="nav-collapse collapse">
                  <ul class="nav">
                    <li><%= link_to "Add new entry", new_user_journal_entry_path(@user, @journal) %>
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><a href="#">Action</a></li>
                      <li><a href="#">Another action</a></li>
                      <li><a href="#">Something else here</a></li>
                      <li class="divider"></li>
                      <li class="nav-header">Nav header</li>
                      <li><a href="#">Separated link</a></li>
                      <li><a href="#">One more separated link</a></li>
                    </ul>
                    </li>
                    <li class="journal-name"><%= link_to "Journal: #{Journal.find(params[:journal_id]).name}", user_journals_path(@user) %></li>
                  </ul>
                  <!-- 
                  <form class="navbar-form pull-right">
                    <input class="span2" type="text" placeholder="Email">
                    <input class="span2" type="password" placeholder="Password">
                    <button type="submit" class="btn">Sign in</button>
                  </form>
                  -->
                </div><!--/.nav-collapse -->
              </div>
            </div>
          </div>

          <div class="container">

            <!-- Main hero unit for a primary marketing message or call to action -->
            <div class="hero-unit">
              <h1>LiveJournal</h1>
              <h2 style="margin-left: 200px; color: orange;"><%= @journal.name %></h2>
            </div>

            <!-- Example row of columns -->

            
            <% @entries.reverse.each do |entry| %>
              <article>
                <header>
                  <h1><%= entry.title %></h1>
                </header>
                <p><%= entry.body %></p>
                <footer>
                <p>posted 
                  <span class="date"><%= entry.created_at %></span> by 
                  <span class="posted-name"><%= @user.full_name %></span></p>
                <span id="entry-controls">
                  <%= link_to 'Edit', edit_user_journal_entry_path(@user, @journal, entry) %> | <%= link_to 'Delete', user_journal_entry_path(@user, @journal, entry), :method => "DELETE" %>
                </span>
                </footer>
              </article>
              <br />
            <% end %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @entry.title %>
</p>

<p>
  <b>Body:</b>
  <%= @entry.body %>
</p>


<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/journals/_form.html.erb
<%= form_for([@user, @journal]) do |f| %>
  <% if @journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
      <% @journal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :private %><br />
    <%= f.check_box :private %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/journals/edit.html.erb
<h1>Editing journal</h1>

<%= render 'form' %>

<%= link_to 'Show', @journal %> |
<%= link_to 'Back', user_journals_path %>

app/views/journals/index.html.erb
<h1>Listing journals</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Private</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @journals.each do |journal| %>
  <tr>
    <td><%= journal.name %></td>
    <td><%= journal.description %></td>
    <td><%= journal.private %></td>
    <td><%= journal.user_id %></td>
    <td><%= link_to 'Show', user_journal_path(@user, journal) %></td>
    <td><%= link_to 'Edit', edit_user_journal_path(@user, journal) %> | <%= link_to 'Delete', user_journal_path(@user, journal), :method => "DELETE" %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Journal', new_user_journal_path(@user) %>

app/views/journals/new.html.erb
<h1>New journal</h1>

<%= render 'form' %>

<%= link_to 'Back', user_journals_path(@user) %>

app/views/journals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @journal.name %>
</p>

<p>
  <b>Description:</b>
  <%= @journal.description %>
</p>

<p>
  <b>Private:</b>
  <%= @journal.private %>
</p>

<p>
  <b>User:</b>
  <%= @journal.user_id %>
</p>


<%= link_to 'Back', user_journals_path(@user) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Journalv2</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
    <%= stylesheet_link_tag    "style", :media => "all" %>
    <%= stylesheet_link_tag    "main", :media => "all" %>

    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <style>
      body {
        padding-top: 150px;
        padding-bottom: 40px;
      }
    </style>
  </head>


  <%= yield %>

</body>
</html>

app/views/main/index.html.erb
<h1>Main page</h1>

<div class="post_container">


<p>Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.</p>
<p>Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.</p>
<p>Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.</p>
<p>Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.  Lorem Ipsum.</p>

</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th>Password confirmation</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.password %></td>
    <td><%= user.password_confirmation %></td>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.active %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Password confirmation:</b>
  <%= @user.password_confirmation %>
</p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Active:</b>
  <%= @user.active %>
</p>


-----


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>